Lecture 2/2/2021 - Broadcasting, NumPy, and Timing Magics

In [1]:
#column and row vectors
#check size, shape, ndim

import numpy as np
x = np.array([[1, 2, 3],   #creating a 2D array 
             [4, 5, 6], 
             [7, 8, 9]])

y = np.array([2, 1, 0]) #numbers can be seen as being in a row

x + y #2 in y adds to the first column of x, 1 in y adds to the second column of x, 0 in y adds to the third column in x

array([[3, 3, 3],
       [6, 6, 6],
       [9, 9, 9]])

In [2]:
x = np.array([[1, 2, 3], 
             [4, 5, 6], 
             [7, 8, 9]])

y = np.array([[2],   #brackets around individual numbers now means they are seen as in a column
              [1], 
              [0]])

x + y # 2 in y added to the first row of x, 1 in y added to the second row in x, 0 in y added to the third row in y

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [3]:
#error example

x = np.array([[1, 2, 3], 
             [4, 5, 6], 
             [7, 8, 9]])

y = np.array([[2],   
              [1]])

x + y #returns an error, can't be broadcast with shapes. x and y are not the same shape

ValueError: operands could not be broadcast together with shapes (3,3) (2,1) 

In [4]:
y = np.array([1]) #create np.array with 1

y.size #1       
y.shape #(1,)        
y.ndim #1
#in panda series the ndim is always 1, but in numpy the ndim is contingent on the number in the array

1

In [5]:
y = np.array([[1]])

y.size #1
y.shape #(1, 1)  
y.ndim #2       2 dimnesional array

#a size just gets you a number of elements in that array
#shape is a tuple with the shape
#however many numbers in that tuple that gives the dimension

2

In [6]:
y = np.array([[[1]]])

y.size #1
y.shape #(1, 1, 1)
y.ndim #3            the tuple has 3 numbers an x, y, and z

3

In [7]:
#brief linear algebra
x = np.array([[1, 2, 3],   #3 rows 3 columns
             [4, 5, 6],
             [7, 8, 9]])
y = np.array([[2],         #1 column
              [1],
              [0]])

x * y #mutiply 2 from y with first row of x, multiply 1 from y with second row of x, multiply 0 from y with third row of x
v = np.matmul(x, y)  #matmul  multiplies matricies
v
v.T #transpose flipping rows and columns

array([[ 4, 13, 22]])

In [11]:
C = np.array([[-10, 12], #C * 1.8 + 32
              [20, 34]]) #C * 1 + 273.15
#first row: convert to Fahrenheit 
#second row: convert to Kelvin
T = C * np.array([[1.8], [1]]) + np.array([[32], [273.15]]) #1.8 is muliplied to -10 and 20 is multiplied to 1 and then answer from 1.8 and -10 are added to 32 and answer from 20 and 1 is added to 273.15
T

array([[ 14.  ,  53.6 ],
       [293.15, 307.15]])

In [9]:
#timit inline
%timeit 2 +3 #times everything in single line
%timeit 2 == 3 #required to use % for each line to get the time of that line

6.34 ns ± 0.0158 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)
21.5 ns ± 0.126 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [10]:
%%timeit #%% times everything in this code block
def addition(x, y):
    return x+y

50.4 ns ± 0.201 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
